version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tutbase
      POSTGRES_PASSWORD: tutbase
      POSTGRES_USER: tutbase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data